// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Block struct {
	ID        uuid.UUID
	BlockerID uuid.UUID
	BlockedID uuid.UUID
	CreatedAt sql.NullTime
}

type Conversation struct {
	ID        uuid.UUID
	User1ID   uuid.UUID
	User2ID   uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type ConversationRead struct {
	UserID         uuid.UUID
	ConversationID uuid.UUID
	LastReadAt     sql.NullTime
}

type Message struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	SenderID       uuid.UUID
	Content        string
	ReplyToID      uuid.NullUUID
	CreatedAt      sql.NullTime
	ReadAt         sql.NullTime
	EditedAt       sql.NullTime
	DeletedAt      sql.NullTime
}

type MessageReaction struct {
	ID        uuid.UUID
	MessageID uuid.UUID
	UserID    uuid.UUID
	Emoji     string
	CreatedAt sql.NullTime
}

type PinnedConversation struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	ConversationID uuid.UUID
	PinnedAt       sql.NullTime
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	CreatedAt sql.NullTime
}

type User struct {
	ID               uuid.UUID
	GithubID         int32
	Username         string
	DisplayName      sql.NullString
	Email            sql.NullString
	AvatarUrl        sql.NullString
	AccessToken      sql.NullString
	HasAccount       sql.NullBool
	LastSeenAt       sql.NullTime
	HideOnlineStatus sql.NullBool
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}
