// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    github_id,
    username,
    display_name,
    email,
    avatar_url,
    access_token,
    has_account
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, github_id, username, display_name, email, avatar_url, access_token, has_account, last_seen_at, hide_online_status, created_at, updated_at
`

type CreateUserParams struct {
	GithubID    int32
	Username    string
	DisplayName sql.NullString
	Email       sql.NullString
	AvatarUrl   sql.NullString
	AccessToken sql.NullString
	HasAccount  sql.NullBool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.GithubID,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.AvatarUrl,
		arg.AccessToken,
		arg.HasAccount,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.AccessToken,
		&i.HasAccount,
		&i.LastSeenAt,
		&i.HideOnlineStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByGithubID = `-- name: GetUserByGithubID :one
SELECT id, github_id, username, display_name, email, avatar_url, access_token, has_account, last_seen_at, hide_online_status, created_at, updated_at FROM users
WHERE github_id = $1
LIMIT 1
`

func (q *Queries) GetUserByGithubID(ctx context.Context, githubID int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGithubID, githubID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.AccessToken,
		&i.HasAccount,
		&i.LastSeenAt,
		&i.HideOnlineStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, github_id, username, display_name, email, avatar_url, access_token, has_account, last_seen_at, hide_online_status, created_at, updated_at FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.AccessToken,
		&i.HasAccount,
		&i.LastSeenAt,
		&i.HideOnlineStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, github_id, username, display_name, email, avatar_url, access_token, has_account, last_seen_at, hide_online_status, created_at, updated_at FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.AccessToken,
		&i.HasAccount,
		&i.LastSeenAt,
		&i.HideOnlineStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, github_id, username, display_name, email, avatar_url, access_token, has_account, last_seen_at, hide_online_status, created_at, updated_at
FROM users
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GithubID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.AvatarUrl,
			&i.AccessToken,
			&i.HasAccount,
			&i.LastSeenAt,
			&i.HideOnlineStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setHasAccount = `-- name: SetHasAccount :exec
UPDATE users
SET has_account = TRUE
WHERE id = $1
`

func (q *Queries) SetHasAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setHasAccount, id)
	return err
}

const setOnlinePrivacy = `-- name: SetOnlinePrivacy :exec
UPDATE users
SET hide_online_status = $2
WHERE id = $1
`

type SetOnlinePrivacyParams struct {
	ID               uuid.UUID
	HideOnlineStatus sql.NullBool
}

func (q *Queries) SetOnlinePrivacy(ctx context.Context, arg SetOnlinePrivacyParams) error {
	_, err := q.db.ExecContext(ctx, setOnlinePrivacy, arg.ID, arg.HideOnlineStatus)
	return err
}

const updateAccessToken = `-- name: UpdateAccessToken :exec
UPDATE users
SET access_token = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateAccessTokenParams struct {
	ID          uuid.UUID
	AccessToken sql.NullString
}

func (q *Queries) UpdateAccessToken(ctx context.Context, arg UpdateAccessTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateAccessToken, arg.ID, arg.AccessToken)
	return err
}

const updateLastSeen = `-- name: UpdateLastSeen :exec
UPDATE users
SET last_seen_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateLastSeen, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    display_name = $2,
    email = $3,
    avatar_url = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, github_id, username, display_name, email, avatar_url, access_token, has_account, last_seen_at, hide_online_status, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          uuid.UUID
	DisplayName sql.NullString
	Email       sql.NullString
	AvatarUrl   sql.NullString
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.Email,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.AccessToken,
		&i.HasAccount,
		&i.LastSeenAt,
		&i.HideOnlineStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
